name: ${pluginName}
main: vg.civcraft.mc.civchat2.CivChat2
version: ${version}
authors:
- jjj5311
- Maxopoly
depend:
- NameLayer
- CivModCore
description: ${description}
api-version: ${api_version}
permissions:
  CivChat2.*:
    description: Gives access to /sayall
    default: op
  civchat2.globalmute:
    description: Gives access to the global mute command
    default: op
  civchat2.leavejoinimmune:
    description: Disables a player broadcasting Leave/Join messages
    default: op
